depromeet/Ding-dong-fe

.github/ISSUE_TEMPLATE/docs.md, .github/ISSUE_TEMPLATE/feat.md, .github/ISSUE_TEMPLATE/fix.md, .github/ISSUE_TEMPLATE/refactor.md, .github/ISSUE_TEMPLATE/style.md, .github/PULL_REQUEST_TEMPLATE.md, .gitignore
- gitignore file에 editor, pnpm 관련 파일을 추가합니다. [9f90cf5](https://github.com/depromeet/13th-7team-fe/pull/2/commits/9f90cf55ecbd5ada245218d334bba439cd715b01)
- pull request template을 추가합니다. [14faa94](https://github.com/depromeet/13th-7team-fe/pull/2/commits/14faa94b48e968661accb05b86b78f79e28331ac)
- issue template을 추가합니다. [533b0db](https://github.com/depromeet/13th-7team-fe/pull/2/commits/533b0db6af66b528fc41b7877a9cac84c5d56736)
- pull request 컨밴션, 커밋 메시지 컨밴션, github 세팅(reviewer, label, milestone) 을 정하기 위한 PR입니다.
코드 위주로 봐주시면 감사하겠습니다.
[gitignore - 디프만의 toks-web 참고](https://github.com/depromeet/toks-web/blob/dev/.gitignore)
[pull request template - 노션 참고](https://www.notion.so/depromeet/986e4f7f238d4b20a08013cbf9ae6bdb?pvs=4#8a1258d22d9f4b9086d94e6489c4f315)
[issue template - ygtang-client …
=> Add gitignore and pull request template

.github/workflows/chromatic.yml, build-storybook.log, package.json, pnpm-lock.yaml
chromatic 패키지 설치 및 github-action 스크립트 작성
[우리팀 choromatic](https://www.chromatic.com/builds?appId=6478b0e59073c507c3cc3944)
- UI개발 진행 상황을 공유
- [스토리북-공식문서](https://storybook.js.org/docs/react/sharing/publish-storybook)에서 배포를 통해 공유할 수 있는 방법을 소개해둔 문서
무료이면서 설치방법 및 배포 방법도 공식문서 친절히 나와있어 쉽게 적용할 수 있었습니다. 혹시 설치 및 가입 과정에서 어려움이 있다면 슬랙으로 소환해주세요. 바로 갈게여 🏃‍♂️
- https://www.chromatic.com
=> Dep 42 chromatic

.env.production, .gitignore
=> Chore: gitignore 파일 수정

pnpm-lock.yaml
=> Refactor: pnpm-lock.yaml 중복 설정 제거

.github/CODEOWNERS
- CODEOWNERS file을 추가합니다.
해당 PR 머지 이후 PR을 생성할 경우 13th-7team-fe-review 와 연결되어서 reviewer가 자동 세팅됩니다.
[Code Owner로 Auto Assing하기 - blog](https://helloinyong.tistory.com/329)
=> Add Add CODEOWNERS file

.github/workflows/chromatic.yml, .github/workflows/ci.yml, .storybook/preview.tsx, next.config.js, package.json, src/app/layout.tsx, src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Button/index.ts, src/components/Popup/Popup.stories.tsx, src/components/Popup/Popup.tsx, src/components/Popup/index.ts, src/components/Portal/Portal.tsx, src/components/Portal/index.ts, src/hooks/useIsMounted.ts, src/hooks/usePopup.ts
디자인 시스템(버튼, 팝업) 구현하였습니다!
1. `button`
버튼 색상은 primary, secondary 둘 중에 하나이고, 사이즈는 small, medium, large 중에 하나 입니다.
채린님이 주신 버튼은 사이즈에 따라 height가 자동으로 적용되고, width는 버튼을 사용할 때마다 지정해주어야합니다! (width 지정해주지 않을시 100% => width 100% 버튼이 많다고 하셔서 디폴트로 지정해두었습니다.)
```
// 사용 예시
<Button size="medium" color="primary">{'버튼'}</Button>
```
2. `popup`
popup은 크게 positive(확인 버튼만 있는 경우),basic(확인 + 취소 버튼이 있는 경우) 입니다.
createPortal를 이용해 구현하였고, portal 컴포넌트에 framer-motion 라이브러리를 사용해 감싸주어서 팝업을 열때 좀 더 생동감있도록 구현하였습니다. 💫
추가로 popup 사용을 편하게 하기 위해서 ```usePopup``` 커스텀 훅을 만들어 두었습니다.
```
// 사용 예시
const { isOpen, open, close } = usePopup();
<Popup
isOpen={isOpen}
title="title"
description="description"
buttons={
<Button size="medium" color="secondary" onClick={close}>
{'버튼'}
</Button>
}
/>
```
+) 추가로 ‼️
윤호님이 …
=> Dep 38 fe button popup component

src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.tsx, src/components/Tag/index.ts, src/types/user.d.ts, tailwind.config.js
Tag 컴포넌트를 구현했어요!
Tag 컴포넌트를 구현하였고, 추가적으로 tailwind.config.js에 색상을 추가했습니다.
[여기](https://www.figma.com/file/TqXqE20VX7V1sw71TYj8qO/DD-_-WIRE-FRAME?type=design&node-id=186-2498&t=DSFFAyOjBZnv6QQt-0)를 보시면 캐릭터에 따라서 태그나 주민증, 주민증 세부 색상들이 달라져서 디자인팀이 주신 디자인시스템의 colors에는 없지만 tailwind.config.js에 추가하였어요!
=> Dep 58 fe tag component

src/mocks/index.ts
> @Dongkyuuuu  감사합니당👏👏👏👏👏👏👏
동규님 도움으로 msw 에러를 해결했습니다. 원인은 찾아봤는데 잘 모르겠네요...
`mocks/initMock.ts`에서 모듈 import를 require로 변경하니까 아래와 같은 문제가 해결됐어요.
**원래 방식의 문제**
> 첫 렌더링시 서비스 워커 등록이 되지 않아 네트워크 오류가 발생하는 문제 (api 호출 → 서비스 워커 등록 : 에러발생)
```diff
- const { server } = await import('./server');
+ const { server } = await require('./server');
- const { worker } = await import('./browser');
+ const { worker } = await require('./browser');
```
=> Feat: MSW 설정 변경

package.json
도커 실행문제로 package.json 스크립트 명령어 수정
빌드만 확인해야합니다
=> Dep 32 FE CI/CD 

Dockerfile
=> build: edit dockerfile

teamp.md
=> c 테스용입니다..

src/components/Chip/Chip.tsx, src/components/KeywordInput/KeywordInput.tsx, src/modules/IdCardCreation/Step/BoardingStep.client.tsx, src/modules/IdCardCreation/Step/LoadingStep.client.tsx, src/modules/IdCardCreation/Step/ProfileStep.client.tsx, tailwind.config.js
1. tailwind.config에서 px단위를 pxr로 수정했어요.
앞으로 rem을  사용하실 경우 tailwind의 기본 값이 아닌 pxr 단위를 사용하시면 됩니다. 
```diff
- className="mt-4"  (1rem)
+ className="mt-16pxr" (1rem)
```
2. fontsize에서도 pxr을 사용할 수 있습니다. 선언부분은 아래 댓글을 참고해주세요. 
프로젝트에서 기존에 설정된 px단위는 모두 pxr로 변경했어요. 
ex)
```diff
- className="mb-28px flex min-h-[56px] bg-grey-50 px-20px py-12px"
+ className="mb-28pxr flex min-h-[56px] bg-grey-50 px-20pxr py-12pxr"
```
=> Dep 84 pxr

src/app/id-card/[id]/page.tsx, src/components/Tag/Tag.tsx, src/lib/api/domain/idCard.api.ts, src/mocks/idCard/idCard.mock.ts, src/modules/IdCard/IdCard.client.tsx, src/modules/IdCardDetail/Intro/Intro.server.tsx, src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.server.tsx, src/types/api/response.type.ts, src/types/auth/model.type.ts, src/types/auth/response.type.ts, src/types/community/index.ts, src/types/community/model.type.ts, src/types/community/response.type.ts, src/types/idCard/index.ts, src/types/idCard/model.type.ts, src/types/idCard/request.type.ts, src/types/idCard/response.type.ts, src/types/user/index.ts, src/types/user/model.type.ts, src/types/user/request.type.ts, src/types/user/response.type.ts
오늘 회의에서 논의한 Type -> Model 로 수정했습니다.
1. dto.type 파일에서 model.type으로 수정했습니다. 
2. 컴포넌트 명과 충돌하여 Model를 타입뒤에 붙이기로 했습니다.
3. Response, Request는 Model를 붙이지 않습니다.
=> Refactor api type

package.json, pnpm-lock.yaml, src/components/KeywordInput/KeywordInput.tsx, src/components/KeywordInput/useInputAutoSize.ts, src/components/KeywordInput/useKeywordInput.hooks.ts, src/components/ProfileImageEdit/ProfileImageEdit.client.tsx, src/lib/api/config/api.types.ts, src/modules/IdCardCreation/Card/KeywrodContentEditCard.client.tsx, src/modules/IdCardCreation/Step/KeywordContentImage.client.tsx
=> Refactor type error

.storybook/preview.tsx
=> Fix: storybook alias

src/components/Button/Button.tsx
버튼의 크기가 height로 조정이 되어있었는데 padding으로 수정했습니다. 
=> Refactor: button height -> padding으로 수정

.storybook/preview.tsx, src/components/BottomNavigation/BottomNavigation.tsx, src/components/TopNavigation/TopNavigationWrapper.tsx, src/styles/globals.css, tailwind.config.js
1. 레이아웃 관련 tailwind.cofing 변수 설정
2. max-width 설정
3. 스토리북 기본 layout 제거
1. 레이아웃 관련 tailwind.cofing 변수 설정
> 네이밍 추천받아요... 😅
```js
spacing: {
't-nav': '50px',
'b-nav': '52px',
'layout-sm': '20px',
'layout-l': '28px',
...declarePxr(),
},
```
예시
```diff
- h-[52px]
+ h-b-nav 
```
2. max-width 설정
4. 스토리북 기본 layout 제거
preview.ts에 parameters로 아래와 같은 설정 추가
```
layout: 'fullscreen',
```
- https://github.com/storybookjs/storybook/issues/12109
=> Dep 90 layout variable

src/components/BottomNavigation/BottomNavigation.stories.tsx, src/components/BottomSheet/BottomSheet.stories.tsx, src/components/Button/Button.stories.tsx, src/components/Button/TextButton.stories.tsx, src/components/Chip/Chip.stories.tsx, src/components/Icon/Icon.stories.tsx, src/components/KeywordInput/KeywordInput.stories.tsx, src/components/Menu/Menu.stories.tsx, src/components/Popup/Popup.stories.tsx, src/components/Swiper/Swiper.stories.tsx, src/components/Tag/Tag.stories.tsx, src/components/TextArea/TextArea.stories.tsx, src/components/TextInput/TextInput.stories.tsx, src/components/TopNavigation/TopNavigation.stories.tsx, src/modules/CommunityDetail/CommunityDetail.stories.tsx, src/modules/IdCard/IdCard.stories.tsx, src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx, src/modules/IdCardDetail/Intro/Intro.stories.tsx, src/modules/IdCardDetail/KeywordContentCard/KeywordContentCard.stories.tsx, src/modules/IdCardEditor/IdCardEditorSteps.stories.tsx, src/modules/PlanetEnterButtons/PlanetEnterButton.stories.tsx
스토리북 네이밍 컨벤션 설정
```
components/**
modules/**
pages/**
```
=> Rename: storybook convention

src/api/domain/community.api.ts, src/api/domain/idCard.api.ts, src/app/planet/[id]/page.tsx, src/mocks/community/community.mock.ts, src/mocks/community/community.mockHandler.ts, src/mocks/idCard/idCard.mockHandler.ts, src/modules/CommunityIdCards/CommunityIdCards.client.tsx, src/types/community/model.type.ts, src/types/community/request.type.ts, src/types/community/response.type.ts
1. 유저가 속한 커뮤니티 리스트 불러오기 api를 추가했어요
2. id 명명한 것들을 구체적으로 communityId, idCardId로 수정했어요
=> Dep 97 change planet

src/app/my-page/edit/page.tsx
=> Fix: mypage build error 수정

src/api/domain/idCard.api.ts, src/app/my-page/layout.tsx, src/app/my-page/page.tsx, src/mocks/idCard/idCard.mockHandler.ts, src/modules/IdCardEditButton/IdCardEditButton.client.tsx, src/modules/IdCardEditButton/IdCardEditButton.stories.tsx, src/modules/IdCardEditButton/index.ts, src/modules/PlanetCreationButton/PlanetCreationButton.client.tsx, src/modules/PlanetCreationButton/PlanetCreationButton.stories.tsx, src/modules/PlanetCreationButton/index.ts, src/types/idCard/response.type.ts
my-page에 필요한 모듈 작업 및 api 설정
모듈 개발
- [Feat: PlanetCreationButton](https://github.com/depromeet/Ding-dong-fe/commit/af7f73df62e2b84d911b5b7a97f56c56aa10cd09) : 여러 곳에서 반복되는 컴포넌트여서 분리했어요.
- [Feat: IdCardEditButton](https://github.com/depromeet/Ding-dong-fe/commit/75fa7e1aba3e82895f4cdb5f5358219690909e98) : 수정 버튼입니다. page가 서버 컴포넌트인데, 버튼은 클라이언트 컴포넌트여서 분리할 필요가 있어서 분리했어요. my-page 내부에 넣을까하다가 별도의 모듈로 분리했어요. 
이후 작업
- https://github.com/depromeet/Ding-dong-fe/pull/73 해당 pr이 머지되면 행성 id를 받아서 api를 요청할 예정입니다~
🚨에러
빌드시 [Error Dynamic server usage: cookies](https://www.notion.so/depromeet/Error-Dynamic-server-usage-cookies-d4a82128d99e4009b03f2a95e5befd64?pvs=4) 관련 에러가 발생해요.  ([슬랙](https://depromeet13th.slack.com/archives/C052G0MBG3V/p1687011686790039)에서 언급한 내용과 동일한 에러입니다)
그런데 이게 로그인 처리 때문에 발생하는 에러인지, 다른 …
=> Dep 110 my page

src/app/my-page/page.tsx
[이 문제](https://www.notion.so/depromeet/Error-Dynamic-server-usage-cookies-d4a82128d99e4009b03f2a95e5befd64?pvs=4) 해결 했어요!
=> Fix: dynamic 페이지로 수정

src/components/ProgressBar/ProgressBar.stories.tsx, src/components/ProgressBar/ProgressBar.tsx, src/components/ProgressBar/index.ts, src/components/TopNavigation/TopNavigation.stories.tsx, src/components/TopNavigation/TopNavigationProgressBar.tsx, src/components/TopNavigation/index.tsx, src/modules/IdCardCreation/Form/IdCardCreationForm.tsx, src/types/image/model.type.ts, tailwind.config.js
- progress bar를 추가합니다.
- top navigation 에 progress bar를 추가합니다.
- 주민증 생성 로직에 추가합니다.
- [progress bar storybook](http://localhost:6006/?path=/story/components-progressbar--defulat)
- [top navigation storybook](http://localhost:6006/?path=/story/components-topnavigation--title-with-progress-bar)
- [주민증 생성 storybook](http://localhost:6006/?path=/story/modules-idcardsteps--default)
[Figma](https://www.figma.com/file/TqXqE20VX7V1sw71TYj8qO/DD-_-WIRE-FRAME?type=design&node-id=475-6473&t=I62TGDpPTHMpifYo-4)
[animation 참고 블로그](https://alvarotrigo.com/blog/progress-bar-css/)
[animation 참고 codepen](https://codepen.io/alvarotrigo/pen/rNGOpZM)
=> Add progress bar 

src/components/Swiper/SwiperSlide.tsx
다래님이 찾아주신 swiper 관련 에러를 수정했어요 😅
해결 방법
`src/components/Swiper/SwiperSlide` 컴포넌트에 아래와 같은 속성 추가 (https://github.com/nolimits4web/swiper/issues/4413#issuecomment-1021387492)
```
SwiperSlide.displayName = 'SwiperSlide';
```
문제 원인
- next 환경에서 swiper 클래스 태그 밖에 자식이 렌더링되는 현상
next
```tsx
<div class="swiper-wrapper"></div>
<div class="swiper-slide"></div>
<div class="swiper-slide"></div>
```
sb
```tsx
<div class="swiper-wrapper">
<div class="swiper-slide"></div>
<div class="swiper-slide"></div>
</div>
```
https://github.com/nolimits4web/swiper/issues/4413
=> Refactor: Swiper 에러 수정

src/api/domain/comment.api.ts, src/app/id-card/[id]/page.tsx, src/mocks/comment/comment.mock.ts, src/mocks/comment/comment.mockHandler.ts, src/mocks/handlers.ts, src/modules/Comment/Comment.client.tsx, src/modules/Comment/index.ts, src/modules/CommentList/CommentList.client.tsx, src/modules/CommentList/index.ts, src/types/comment/index.ts, src/types/comment/model.type.ts, src/types/comment/request.type.ts, src/types/comment/response.type.ts
댓글 관련 스키마 타입 
댓글 관련 GET 요청 세팅 (api, mock handler)
=> Dep 127 comment schema

src/api/domain/community.api.ts, src/api/domain/idCard.api.ts, src/app/id-card/[id]/page.tsx, src/app/my-page/config/page.tsx, src/app/planet/[id]/page.tsx, src/components/HydrationProvider/HydrationProvider.tsx, src/components/HydrationProvider/index.ts, src/modules/CommunityIdCards/CommunityIdCards.client.tsx, src/modules/PlanetSelector/CommunityList.client.tsx, src/types/community/request.type.ts
prefetch 편하게 쓰기 위한 컴포넌트를 만들었어요.
1. id가 string으로 되어있는것들을 number로 수정했어요.
2. hydrate 방식으로 pre-fetch할 때 편하게 사용하기 위한 `HydrationProvider` 컴포넌트를 추가했어요.
=> Prefetch util

src/components/Template/TemplateButton.tsx
https://github.com/depromeet/Ding-dong-fe/pull/95#issuecomment-1601138379 
Button은 named export여서 import 형식을 수정했어요
=> Template button 빌드 에러 경로 수정

src/api/domain/comment.api.ts, src/mocks/comment/comment.mockHandler.ts, src/types/comment/request.type.ts, src/types/comment/response.type.ts
=> Dep 143 comment api

src/mocks/comment/comment.mock.ts, src/modules/CommentList/Comment/Comment.client.tsx, src/modules/CommentList/Comment/Comment.stories.tsx, src/modules/CommentList/CommentCommon/Content.client.tsx, src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
댓글 상세보기 관련 요구사항
전제 조건: 너비에 상관없이 5줄이 넘어가면
활용한 주요 css 속성
- [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle): 인자로 전달받은 요소의 모든 CSS 속성값을 담은 객체 반환
- [getPropertyValue](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyValue) : 지정한 속성의 css 값을 가져오는 함수
- [lineHeight](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height): 글자(p태그)의 높이 (1줄)
- [offsetHeight](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight): 마진을 제외한 높이(border, padding포함)
- [line-clamp](https://developer.mozilla.org/ko/docs/Web/CSS/-webkit-line-clamp): CSS 속성은 블록 컨테이너의 콘텐츠를 지정한 줄 수만큼으로 제한
📌 요소의 순수한 높이 얻기
clientHeight를 활용할까했지만 clientHeight는 margin과 border만 제외하고 padding은 포함되네요. 
margin, border, padding 모두를 제거한 순수한 요소의 높이를 얻는 속성이 없어서 …
=> Dep 130 comment detail

src/api/domain/comment.api.ts, src/api/domain/community.api.server.ts, src/api/domain/community.api.ts, src/api/domain/idCard.api.server.ts, src/api/domain/user.api.ts, src/app/accounts/page.tsx, src/app/id-card/[id]/page.tsx, src/app/planet/[id]/page.tsx, src/components/Divider/Divider.tsx, src/components/Icon/Icon.stories.tsx, src/components/Icon/SendIcon.tsx, src/components/Icon/index.tsx, src/components/TextInput/TextInputBorder.tsx, src/mocks/handlers.ts, src/mocks/user/user.mock.ts, src/mocks/user/user.mockHandler.ts, src/modules/CommentInput/CommentInput.client.tsx, src/modules/CommentInput/CommentInput.stories.tsx, src/modules/CommentInput/index.ts
1. 댓글 작성하기 컴포넌트를 구현했습니다.
2. user info(profile)를 가져오는 api를 추가했습니다.
댓글 작성하는 CommentInput 컴포넌트를 구현했어요.
댓글 작성해서 api 연결하는 작업은 지금도 양이 좀 있어서 review하기 수월하도록 다음 pr에서 하도록 하겠습니다! 
UI만 봐주시면 될 것 같아요~!
세부 내용들은 댓글 달았습니다 !
캐시 때문인지 로컬 스토리북에서는 잘 보이는데, chromatic 에서는 잘 안보여서 사진 첨부 합니다!
|     x    |  <img width="378" alt="스크린샷 2023-06-23 오전 12 23 28" src="https://github.com/depromeet/Ding-dong-fe/assets/62633444/257ae1fb-fe84-4bac-a397-814f0b985fc2">     |
=> Dep 149 input comment ui

src/utils/auth/error.ts, src/utils/auth/getUserId.client.ts, src/utils/auth/getUserId.server.ts
getUserIdClient, getUserIdServer 유틸을 추가했어요.
- 환경에 맞게 userId를 불러올 수 있는 함수입니다.
- number 혹은 undefined를 반환합니다.
=> Get user id

src/api/domain/comment.api.server.ts, src/api/domain/comment.api.ts, src/app/id-card/[id]/page.tsx, src/mocks/comment/comment.mock.ts, src/mocks/comment/comment.mockHandler.ts, src/modules/CommentList/Comment/Comment.client.tsx, src/modules/CommentList/Comment/Comment.stories.tsx, src/modules/CommentList/CommentList.client.tsx, src/modules/CommentList/CommentReplyList/CommentReply.client.tsx, src/modules/CommentList/CommentReplyList/CommentReplyList.client.tsx, src/types/comment/model.type.ts, src/types/comment/request.type.ts
CommendModel에 idCardId 타입이 추가됐어요
네이밍 수정 idCardsId -> idCardId로 수정했어요
=> Dep 159 comment scheme

src/app/planet/[id]/components/CommunityIdCards/CommunityIdCards.client.tsx
주민증 없을 경우 [우리 행성 주민을 소개할게요!] 문구 안보이도록 하기
피그마에 주민증 없을 경우 [우리 행성 주민을 소개할게요!] 문구 안보이도록 하기 부분이 있었는데 누락되어서 이번에 작업했습니다.
=> Feat: idcards 하나도 없을 때 문구 안보여주기

src/api/domain/comment.api.ts, src/modules/CommentInput/CommentInput.client.tsx, src/utils/commentApi.util.ts
대댓글 작성하기 기능을 구현했어요. 
저번 회의 때 언급했지만, 로직이 좀 복잡해요.. 😭
자세한 로직보다는 큰 로직위주로 봐주세욥 
1. 대댓글 작성 (id 임시로)
2. 성공시 => id 갱신(서버에서 받은 성공하면 주는 id)
3. 실패시 => 롤백
`pnpm msw // 실행`
=> Dep 171 reply comment

src/modules/CommentList/CommentCommon/Header.client.tsx, src/modules/Notification/NotificationList.tsx, src/utils/time.util.ts
notifcation에 사용하던 유틸을 checkCreateAtAgo 유틸로 수정했어요. 
댓글 컴포넌트에 checkCreateAtAgo를 적용했어요.
=> Dep 173 comment time

src/api/domain/comment.api.ts, src/components/ConfirmPopup/ConfirmDeleteComment/ConfirmDeleteComment.tsx, src/components/ConfirmPopup/ConfirmDeleteComment/index.ts, src/modules/CommentInput/CommentInput.client.tsx, src/modules/CommentList/Comment/Comment.client.tsx, src/modules/CommentList/CommentCommon/DeleteButton.client.tsx, src/modules/CommentList/CommentCommon/ReportButton.client.tsx, src/modules/CommentList/CommentCommon/index.ts, src/modules/CommentList/CommentReplyList/CommentReply.client.tsx, src/utils/commentApi.util.ts
1. 삭제 버튼을 누르면 삭제 팝업 보여주기
2. 내가 작성한 글은 삭제버튼, 남이 작성한 글은 신고버튼을 보여주기
**밑에 3개만 봐주세요** ㅎㅎ.. 브랜치를 잘못만들어서 전에 작업했던 거 까지 올라갔네요😭 
다음 PR에 api 연결할 것 같습니다 !
=> Dep 174 delete comment

src/api/domain/community.api.ts, src/api/domain/user.api.ts, src/app/invitation/[code]/page.tsx, src/app/page.tsx, src/mocks/community/community.mockHandler.ts, src/mocks/user/user.mock.ts, src/mocks/user/user.mockHandler.ts, src/types/community/model.type.ts, src/types/community/request.type.ts, src/types/community/response.type.ts, src/types/user/model.type.ts, src/types/user/request.type.ts, src/types/user/response.type.ts
- BE api 에 맞게 api를 수정합니다.
(행성 초대 코드 검사, 행성 가입하기, 유저 정보 조회 응답값 추가(가입한 행성 목록))
#135 의 후속 PR입니다.
[Slack](https://depromeet13th.slack.com/archives/C0515CGG9H8/p1688138189895049?thread_ts=1687966028.730999&cid=C0515CGG9H8)
[swagger](http://43.201.214.187/api/swagger-ui/index.html)
=> Dep 181 Fix validating invitation code and joining community api to match BE API

src/modules/PlanetEnterButton/PlanetEnterButton.client.tsx
=> Feat: 행성 만들기 버튼 연결하기

next.config.js
next image 설정을 위해서 config를 추가했어요.
=> Feat: next image 설정을 위한 config 추가

src/api/domain/community.api.ts, src/app/planet/[id]/components/CommunityIdCards/CommunityIdCards.client.tsx, src/mocks/community/community.mockHandler.ts, src/types/community/response.type.ts
=> Fix: 주민증 리스트 response 수정

src/modules/CommunityProfile/CommunityLogoImage.tsx
=> Fix: planet logo image #145

src/modules/IdCardCreation/IdCardCreationSteps.tsx, src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
#151 [API] 주민증 생성 시 400에러
#154 [Client] keyword.content 최신화 안 됨
=> #151, #154 주민증 생성 관련 이슈

src/api/domain/comment/comment.api.ts, src/app/id-card/[id]/components/CommentList/CommentList.client.tsx, src/mocks/comment/comment.mockHandler.ts, src/types/comment/response.type.ts
=> Refactor: comment Dto response 수정

src/modules/IdCardCreation/Form/IdCardCreationForm.tsx
form 태그에서 onSubmit 핸들러가 적용되지 않아 발생하는 문제였어요. 
https://github.com/depromeet/Ding-dong-fe/issues/152
=> #152 주민증 생성 form 태그 onSubmit 수정

src/api/config/requestUrl.ts, src/app/admin/community/create/result/layout.tsx, src/app/admin/community/create/result/page.tsx
초래 링크 복사하기 -> cliboard 복사 및 토스트 알람 
- 팝업제거 -> 공유하기 기능이 추가되면 팝업으로 변경 예정
https://github.com/depromeet/Ding-dong-fe/assets/71386219/07a36ceb-73d7-4935-af59-931d12e11023
카카오톡 초대하기 -> 준비중이라는 메시지
https://github.com/depromeet/Ding-dong-fe/assets/71386219/beab526d-541f-4009-be0e-afd8cd94a8de
https://github.com/depromeet/Ding-dong-fe/issues/144
=> 초대링크 복사 수정

src/app/planet/[communityId]/components/IdCardCreatorButton/IdCardCreatorButton.client.tsx
=> Feat: 주민증 만들기 이동 라우팅 수정

src/api/domain/comment/comment.api.ts, src/api/domain/community.api.ts, src/api/domain/notification.api.ts, src/types/community/model.type.ts, src/types/community/response.type.ts
1. data.hasNext 수정
2. 커뮤니티 유저 정보 가져오기 api 추가
=> Feat: 커뮤니티 유저 정보 가져오기 api 추가

src/modules/Onboarding/Form/CharacterCreationForm.helper.ts
- 캐릭터 생성 시 'PIPI'만 나오는 현상을 수정합니다.
https://github.com/depromeet/Ding-dong-fe/issues/174
=> Fix wrong order of character word

src/components/ErrorBoundary/RetryErrorBoundary.client.tsx
reset errorboundary 디자인을 수정했어요.
=> Feat: 에러바운더리 디자인 수정

src/app/error.tsx
https://github.com/depromeet/Ding-dong-fe/assets/71386219/cb1cdecf-d09a-420a-b2d1-ecbbf03f0f4d
=> Feat: 서비스 전체 에러페이지

src/components/TopNavigation/TopNavigationLeft.tsx, src/modules/CommunityAdmin/CommunityAdmin.tsx
=> CommunityAdmin 완료버튼 UI

src/api/domain/comment/comment.helper.ts
=> Fix: 댓글 삭제

src/components/TopNavigation/TopNavigationLeft.tsx, src/modules/CommunityAdmin/CommunityAdmin.tsx, src/modules/PlanetSelector/PlanetSelector.client.tsx
행성 이름이 최대일 때 UI가 꺠지는 부분을 수정했어요
#202
=> 행성 이름이 최대일 때 UI가 꺠지는 부분을 수정했어요 

src/app/not-found.tsx
404시 홈으로 가기 이동하는 버튼 눌렀을 때 페이지가 렌더링 되지않는 이슈를 해결했어요.
https://github.com/depromeet/Ding-dong-fe/assets/62633444/0897cc95-85e3-4b82-b35c-b7ce2e629bc4
=> Fix: 404 error #239

src/app/route.ts
미로그인시 발생하는 에러를 캐치했어요.
- 로그인 페이지로 보냄
=> feat: 미로그인시 에러 catch

src/api/domain/idCard.api.ts, src/modules/IdCardCreation/IdCardCreationSteps.tsx, src/modules/IdCardCreation/Step/CompleteStep.client.tsx
- 주민증 생성 카드의 완료 단계에서 제목과 캐릭터를 추가합니다.
[이슈](https://depromeet13th.slack.com/archives/C052G0MBG3V/p1688576509707419) 해결한 뒤 테스트 후 머지할 예정입니다.
#243
=> Add title of community and characterType of user on complete step of creating id card

src/api/domain/community.api.server.ts, src/app/my-page/[communityId]/components/MyPageIdCard/MyPageIdCard.tsx, src/app/my-page/[communityId]/page.tsx, src/app/my-page/empty/page.tsx, src/modules/CreateIdCardButton/CreateIdCardButton.client.tsx, src/modules/CreateIdCardButton/CreateIdCardButton.stories.tsx, src/modules/CreateIdCardButton/index.ts, src/modules/IdCardCreation/Step/BoardingStep.client.tsx
- 주민증 생성 boadring페이지에 뒤로가기 버튼
- 주민증이 없는 경우 마이페이지에 접근했을 때 처리
#249
=> 주민증 생성 boadring페이지, 주민증이 없는 경우 마이페이지에 접근했을 때 처리

src/api/domain/comment/comment.api.ts, src/api/domain/user.api.ts, src/components/ConfirmPopup/ConfirmCreateIdCard/ConfirmCreateIdCard.client.tsx, src/components/ConfirmPopup/ConfirmCreateIdCard/ConfirmCreateIdCard.stories.tsx, src/components/ConfirmPopup/ConfirmCreateIdCard/index.ts, src/modules/CommentInput/ActiveCommentInput.client.tsx, src/modules/CommentInput/CommentInput.client.tsx, src/modules/CommentInput/DisabledCommentInput.client.tsx, src/modules/CommunityAdmin/CommunityAdmin.tsx, src/modules/IdCardCreation/Step/ProfileStep.client.tsx, src/modules/Onboarding/Step/CharacterBoardingStep.tsx
- 주민증을 생성하지 않았을 때, 댓글창이 안보이는 이슈
- CharacterBoardingStep 버튼 위치 수정
- (대)댓글 삭제,등록 query에 toast알람 등록
#246 
#247 
#225
=> 주민증을 생성하지 않았을 때, 댓글창이 안보이는 이슈 및 기타 이슈

src/api/domain/comment/comment.api.ts, src/api/domain/comment/comment.helper.ts, src/components/ProfileImageEdit/ProfileImageEdit.client.tsx, src/mocks/comment/comment.mock.ts, src/modules/CommentList/Comment/Comment.client.tsx, src/modules/CommentList/CommentReplyList/CommentReply.client.tsx, src/modules/CommentList/CommentReplyList/CommentReplyList.client.tsx, src/types/comment/model.type.ts
대댓글 DTO 수정 사항 반영
대댓글 dto에는 writerInfo없음
=> 대댓글 DTO 수정 사항 반영 및 #263해결 

src/modules/CommentList/Comment/Comment.client.tsx, src/modules/CommentList/CommentCommon/Header.client.tsx, src/modules/CommentList/CommentReplyList/CommentReply.client.tsx, src/modules/Notification/NotificationItem.tsx, src/modules/Notification/NotificationList.tsx, src/utils/time.util.ts
=> 댓글 작성 시간 및 좋아요 에러 처리

src/api/domain/comment/comment.api.ts, src/api/domain/community.api.server.ts, src/app/planet/[communityId]/page.tsx, src/components/ProfileImageEdit/ProfileImageEdit.client.tsx, src/modules/CommentInput/ActiveCommentInput.client.tsx, src/types/community/model.type.ts
행성페이지 및 마이페이지에서 사용하는 top-nav 수정
- 일반
- 관리자
- 마이페이지
#264
=> 행성 관리자 - 일반 멤버일 때 navi 유형 다르게 적용

src/api/config/customError.ts, src/api/domain/community.api.ts, src/app/invitation/[code]/page.tsx
- 가입한 행성의 초대코드 페이지로 들어올 경우, 행성페이지로 redirect 시켜줍니다.
#281
=> Add redirect when tried to join the planet again

src/components/BottomNavigation/BottomNavigation.tsx
BNB 아이콘 순서를 바꿨어요.
https://www.notion.so/depromeet/Design-BNB-50e808bcd0154cb78c491b426fe024d0?pvs=4
=> Fix: BNB 아이콘 순서 변경

src/styles/globals.css
=> Fix: font 적용

src/api/config/customError.ts, src/api/domain/community.api.ts, src/app/invitation/[code]/page.tsx, src/modules/CommentList/CommentCommon/UserProfile.client.tsx
- develop branch를 main에 머지합니다. 앞으로 Main branch를 기준으로 branch를 땁니다.
=> Merge develop to main

src/modules/IdCardCreation/IdCardCreationSteps.tsx, src/modules/IdCardEditor/IdCardEditor.tsx
- 필수값에 대해서 yup validation을 추가하고 '완료'버튼의  disabled 여부를 추가합니다
[Notion QA](https://www.notion.so/depromeet/FE-d7681d99eb464a47b1850b34e41a26f3)
=> Add idcard editor button disabled when editing id card is not valid

src/app/planet/[communityId]/components/CommunityDetail/CommunityDetail.tsx, src/styles/globals.css, tailwind.config.js
=> Fix: max width 변경

src/api/domain/idCard.api.ts, src/modules/IdCardEditor/IdCardEditor.tsx
주민증 수정 요청이후 api처리(완료, 에러 이후 동작)를 수정했어요. 
- [[FE] - 마이페이지 - 주민증 수정 완료 안됨](https://www.notion.so/depromeet/FE-8edccc86593f412aa2c36086e19435d3?pvs=4)
=> [FE] - 마이페이지 - 주민증 수정 완료 안됨

src/components/Chip/Chip.tsx, src/modules/CommentList/CommentCommon/UserProfile.client.tsx, src/modules/IdCardDetail/Intro.tsx, src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
=> Id card edit design

src/components/ToastMessage/ToastMessageProvider.tsx
=> refactor: 토스트 알람 위치 에러 수정

next.config.js, package.json, pnpm-lock.yaml, sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts
에러 추적을 편하게 하기 위해서 sentry 적용했어요.
=> Feat: sentry 적용하기

src/api/domain/comment/comment.api.ts, src/api/domain/comment/comment.helper.ts, src/mocks/comment/comment.mock.ts, src/modules/CommentList/Comment/Comment.client.tsx, src/modules/CommentList/CommentCommon/Header.client.tsx, src/modules/CommentList/CommentCommon/LikeCount.client.tsx, src/modules/CommentList/CommentCommon/LikeIcon.client.tsx, src/modules/CommentList/CommentReplyList/CommentReply.client.tsx, src/modules/CommentList/useLike.ts, src/types/comment/model.type.ts
- [[FE] 본인이 댓글 좋아요한 하트에 불들어오지않음](https://www.notion.so/depromeet/FE-4e27e2d6177845a7ace8b2b408729fb8?pvs=4)
- [[FE] 댓글 [좋아요]가 있는 경우에만 [좋아요 + n개] 가 노출되어야 한다](https://www.notion.so/depromeet/FE-n-e726085d0e6a4eb88b0e3f74cb1ebf27?pvs=4)
=> 댓글 좋아요 로직 및 UI 수정

src/components/Icon/DashIcon.tsx, src/modules/CommentList/CommentCommon/Content.client.tsx, src/modules/CommentList/CommentCommon/DeleteButton.client.tsx, src/modules/CommentList/CommentCommon/LikeCount.client.tsx, src/modules/CommentList/CommentCommon/ReplyShowButton.client.tsx, src/modules/CommentList/CommentCommon/ReplySubmitButton.client.tsx, src/modules/CommentList/CommentCommon/ReportButton.client.tsx
tw문제로 인해 font가 올바르게 적용되지 않았네요..
=> 댓글 컴포넌트 폰트 수정

.github/workflows/build.yml, .github/workflows/deploy.yml
- main/dev 브랜치에 PR 이 발생할 경우 CI 수행
- [main/dev 브랜치에 Push 가 발생할 경우 CI/CD 수행](https://github.com/depromeet/Ding-dong-fe/pull/299)
|  main/dev 브랜치에 PR 이 발생할 때에도 CD 수행   |  main/dev 브랜치에 PR 이 발생할 때에는 CI 만 수행하도록    |
- [main/dev 브랜치 PR 발생 시 CD 수행 제외 처리](https://github.com/depromeet/Ding-dong-fe/pull/299)
=> Fix Separating main/dev branch PR/Push CI/CD scripts

src/api/domain/community.api.ts, src/app/admin/planet/[id]/components/AdminPlanetDetailPage/AdminPlanetDetailPage.tsx, src/app/admin/planet/[id]/edit/components/PlanetAdminEdit/PlanetAdminEdit.tsx, src/app/planet/[communityId]/components/CommunityDetail/CommunityDetail.tsx, src/modules/CommunityAdmin/CommunityAdmin.stories.tsx, src/modules/CommunityAdmin/CommunityAdmin.tsx, src/modules/CommunityAdmin/CommunityAdminEdit.client.tsx
서버 요청을 hydration으로 수정하고 제거 했어요.
#316 
- [[FE] 행성 관리 - 커버 변경 + 행성 프사 변경이 실시간으로 적용되지 않음](https://www.notion.so/depromeet/FE-9c30e91ac63346f7ba74f6f75c4e45aa?pvs=4)
- [[FE] 행성 관리 - 행성 소개글 관련](https://www.notion.so/depromeet/FE-b4ada249761c459c8f52a1eb24b6aa9e?pvs=4)
=> 행성 수정 이후 최신화 에러 수정

src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
https://www.notion.so/depromeet/FE-0eac6a6bfbd741b6bf2de2369341d350?pvs=4
=> [주민증 수정]  키워트 추가 버튼 뿐만 아니라 키워드 영역을 눌렀을 때도 키워드 추가 페이지 진입

src/modules/CommentInput/CommentInput.client.tsx
=> refactor: 댓글 창 막는 로직 수정

src/app/auth/[...nextauth]/route.ts
=> feat: scope 추가

src/app/my-page/[communityId]/components/MyPageIdCard/MyPageIdCard.client.tsx, src/components/Icon/ChatBubbleIcon.tsx, src/components/Icon/Icon.stories.tsx, src/components/Icon/index.tsx, src/mocks/community/community.mock.ts, src/mocks/idCard/idCard.mock.ts, src/modules/IdCard/IdCard.client.tsx, src/types/community/model.type.ts, src/types/idCard/model.type.ts
CommunityIdCardsModel와 IdCardDetailModel에  commentCount 추가 
GET api/communities/communityId/my-info 현재 본인이 속한 행성 내 정보 조회
GET api/communities/communityId/idCards 행성의 모든 주민증 목록 조회
GET api/communities/communityId/users/idCards 행성의 유저 주민증 조회
=> [FE] [주민증] 댓글 수 노출

src/components/TextArea/TextAreaBorder.tsx, src/components/TextArea/TextAreaContent.tsx, src/components/TextArea/useAutoHeightTextArea.tsx, src/hooks/useForwardRef.hooks.ts, src/modules/CommunityAdmin/CommunityAdminEditForm.client.tsx, src/modules/IdCardCreation/Step/ProfileStep.client.tsx, src/modules/IdCardEditor/Step/EditProfileInfoStep.client.tsx, src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
=> 주민증 생성, 수정 & 행성 소개 입력시 textarea 자동 높이 조절

src/app/my-page/[communityId]/components/MyPageIdCard/MyPageIdCard.client.tsx, src/components/KeywordInput/useKeywordInput.hooks.ts, src/components/ProfileImageEdit/ProfileImageEdit.client.tsx, src/mocks/community/community.mock.ts, src/modules/IdCard/IdCard.client.tsx, src/modules/IdCard/IdCard.stories.tsx, src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx, src/modules/IdCardCreation/Step/CompleteStep.client.tsx, src/types/community/model.type.ts
GET api/communities/communityId/idCards API 수정되면 열릴 예정
=> [FE] 주민증 - 프로필사진 노출 

src/components/TextArea/TextAreaBorder.tsx, src/modules/CommentInput/ActiveCommentInput.client.tsx
=> fix: 댓글 여러줄 작성되도록 수정

src/api/config/interceptor.client.ts, src/api/config/interceptor.server.ts, src/middleware.ts, src/utils/fetch.ts
- 초대 코드 페이지에서 로그인 후 바로 다음 단계로 넘어갈 수 있도록 수정합니다.
~~### Draft
middleware와 route 중 결정되면 수정할 예정입니다.
[Slack](https://depromeet13th.slack.com/archives/C0515CGG9H8/p1689607386242009) 문의 해결 후 테스트 완료한 뒤 머지하겠습니다.~~
#199
=> 초대 코드 페이지에서 로그인 후 바로 다른 페이지로 이동하도록 수정

src/components/ConfirmPopup/useConfirmPopup.ts, src/components/KeywordInput/KeywordInput.tsx, src/modules/IdCardEditor/Step/EditKeywordStep.client.tsx
키워드 삭제하면 내용도 사라진다는 팝업 보이게 수정
https://www.notion.so/depromeet/f9c3df5cbd17483eb571d8c9c3f1a3f1?pvs=4
=> 주민증 수정 : 키워드 삭제시 팝업 노출 안됨

src/modules/CommentInput/ActiveCommentInput.client.tsx
댓글 입력창이 조절되고, 최대 5줄까지 입력될 수 있도록 수정했어요.
=> Fix: 댓글 입력창 조절

src/modules/CommentInput/ActiveCommentInput.client.tsx
프로필사진, send icon은 첫 줄 위치로 고정하였습니다.
=> Fix: comment input ui 수정

src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx, src/modules/IdCardEditor/Step/EditKeywordContentStep.client.tsx
React의 기본적인 규칙을 잘 하자~  map으로 컴포넌트 돌릴 때, Index를 key값으로 사용하지 말기
=> [FE] 주민증 수정시 키워드가 밀려써지는 경우

src/components/BottomNavigation/BottomNavigation.tsx, src/components/BottomSheet/BottomSheet.tsx
=> Fix: bottom nav,sheet max width

src/api/domain/comment/comment.api.ts, src/modules/CommentInput/ActiveCommentInput.client.tsx
대댓글 작성 및 제거 이후 react-query의 comment count관련 키 무효화
=> 대댓글 작성시 댓글 총 개수가 반영되지 않은 버그 수정 및 댓글 작성 후 입력창 초기화

src/api/domain/community.api.ts
=> 행성리스트는 항상 refetch 되게 수정

src/app/layout.tsx, src/app/notification/layout.tsx, src/app/planet/[communityId]/id-card/create/page.tsx, src/modules/CommunityAdmin/CommunityAdmin.tsx, src/modules/CommunityAdmin/CommunityAdminCreate.client.tsx, src/modules/CommunityAdmin/CommunityAdminEdit.client.tsx, src/modules/CommunityAdmin/CommunityAdminEditForm.client.tsx, src/modules/IdCardCreation/Form/IdCardCreationForm.tsx, src/modules/IdCardCreation/Step/CompleteStep.client.tsx, src/modules/Onboarding/Form/CharacterCreationForm.client.tsx, src/modules/Onboarding/Question/CharacterQuestion.tsx, src/styles/globals.css
=> Fix: bg-color 수정

src/modules/Onboarding/Step/CharacterBoardingStep.tsx
=> Fix: onboading image 안보이는 문제

src/app/planet/[communityId]/components/CommunityIdCards/CommunityIdCards.client.tsx, src/app/planet/[communityId]/id-card/[idCardId]/components/CommentList/CommentList.client.tsx, src/modules/CommentInput/ActiveCommentInput.client.tsx, src/modules/CommentInput/CommentInput.client.tsx, src/modules/CommentInput/DisabledCommentInput.client.tsx
=> 댓글 입력 컴포넌트 최대 너비 조정

src/modules/Notification/NotificationNoData.tsx
=> refactor: 데스크톱에서 화면이 길어보이는 버그 수정

src/app/admin/planet/create/result/page.tsx, src/app/auth/signin/page.tsx, src/app/error.tsx, src/app/invitation/[code]/page.tsx, src/app/not-found.tsx, src/app/page.tsx, src/app/planet/[communityId]/page.tsx, src/components/BottomSheet/BottomSheet.tsx, src/modules/Onboarding/Step/CharacterBoardingStep.tsx, src/modules/Onboarding/Step/CharacterCompleteStep.client.tsx, src/styles/globals.css, tailwind.config.js
=> Fix: 모바일에서 scroll 생기는 문제

src/constant/planet.ts, src/middleware.ts, src/modules/PlanetSelector/PlanetSelector.client.tsx, src/stores/community.store.ts
마지막 인덱스 였던  행성 기본 선택자를 0번으로 수정했습니다
그 외 행성선택자 로직에서 필요한 기본 선택자 로직도 수정
=> [FE] 행성 기본선택자 0번 인덱스로 수정

src/api/domain/notification.api.server.ts, src/api/domain/notification.api.ts, src/app/notification/InjectQueryDataNotification.client.tsx, src/app/notification/page.tsx, src/types/notification/response.type.ts
=> 알림 타입 변경 대응

src/api/domain/auth.api.server.ts
=> fix: 서버 reissue api header

src/app/planet/page.tsx
| <img width="1440" alt="스크린샷 2023-07-22 오전 9 31 06" src="https://github.com/depromeet/Ding-dong-fe/assets/71386219/0df67dd5-71a4-4c4a-9e57-92b9449eeac1">      |  <img width="1440" alt="스크린샷 2023-07-22 오전 9 44 32" src="https://github.com/depromeet/Ding-dong-fe/assets/71386219/697cb4ec-2f3b-4792-b703-dbe89fbaa97e">     |
=> 소속된 행성이 없는 페이지에서 상단 회색 여백 제거

src/types/notification/model.type.ts
=> [FE] 알람: 답글 좋아요 타입 추가

src/api/domain/auth.api.server.ts, src/api/fetch/privateFetch.ts, src/api/fetch/publicFetch.ts, src/middleware.ts
=> 토큰 만료시 middleware에서 재발급 처리

src/api/domain/nudge.api.client.ts, src/app/planet/[communityId]/id-card/[idCardId]/components/Nudge/Message/NudgeMessages.tsx, src/app/planet/[communityId]/id-card/[idCardId]/components/Nudge/Nudge.client.tsx, src/types/nudge/request.type.ts
- put api 를 추가합니다.
현재 post api 성공할 경우 idcard detail을  invalidateQuery 하고 있습니다. idcard detail을 새롭게 받아왔을 때, 업데이트되지 않은 값을 받아오고 있어 확인이 필요합니다.
코드 위주로 확인 부탁드립니다.
[swagger](https://ding-dong-planet.com/api/swagger-ui/index.html#/%EC%BD%95%20%EC%B0%8C%EB%A5%B4%EA%B8%B0/updateNudge)
=> Add nudge put api
