depromeet/Ding-dong-fe

- .storybook/main.ts
- .storybook/preview.tsx
- package.json
- pnpm-lock.yaml
- src/styles/globals.css
- storybook viewport addon을 추가합니다.
- global css로 `white-space` 를 추가합니다.
storybook 모든 story에서 확인하실 수 있습니다.
[Storybook Viewport Addon](https://storybook.js.org/docs/react/essentials/viewport)
> Add storybook viewport addon

- .husky/pre-commit
pre-commit husky 명령어를 수정했습니다. 
```diff
- pnpm lint-staged
+ npx lint-staged
```
`pnpm lint`으로 next lint를 실행하거나 `npx lint-staged`로 eslint를 실행했어야하는데, 제가 스크립트를 작성할 때 잘못 작성해서 적용이 안됐나봐요😓 
이제 정상적으로 eslint 에러가 발생할 거에요~
> Refactor: husky lint 명령어 수정

- src/components/Icon/CancelIcon.tsx
- src/modules/IdCardCreation/IdCardCreation.type.ts
- src/modules/IdCardCreation/Step/ImagePreview.client.tsx
- src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
- ImagePreview component를 추가합니다.
- 이미지의 닫기 버튼 스타일을 추가합니다.
- 이미지의 스타일을 추가합니다.
- image input에 대한 label을 추가합니다.
- `useFieldArray` 를 삭제합니다.
전체적인 스타일은 추후 적용할 예정입니다. 로직 위주로 봐주시면 감사하겠습니다.
[storybook](http://localhost:6006/?path=/story/idcardsteps--default)에서 단계를 따라가면 확인하실 수 있습니다.
[Figma](https://www.figma.com/file/TqXqE20VX7V1sw71TYj8qO/DD-_-WIRE-FRAME?type=design&node-id=211-3457&t=lHf4qHpI4Td6xDmA-4)
> Dep69 Add ImagePreview component

- package.json
- pnpm-lock.yaml
- src/app/communities/[id]/layout.tsx
- src/app/communities/[id]/page.tsx
- src/hooks/api/community.query.ts
- src/hooks/api/queryKey.type.ts
- src/lib/api/domain/community.api.ts
- src/lib/tanstackQuery/getQueryClient.tsx
- src/mocks/community/community.mock.ts
- src/mocks/community/community.mockHandler.ts
- src/mocks/handlers.ts
- src/modules/CommnuityIdCards/CommunityIdCards.client.tsx
- src/modules/CommnuityIdCards/index.ts
- src/types/community/model.type.ts
- src/types/community/request.type.ts
- src/types/community/response.type.ts
홈에서 주민증 리스트 무한 스크롤링을 구현했어요!
서버 컴포넌트에서 pre-fetch 하여 1페이지만을 보여주고, 클라이언트 컴포넌트로 데이터를 보내 (실제로는 props로 데이터를 보내는 방식이 아닌 react-query 의 Hydrate 요소를 클라이언트 컴포넌트로 래핑해서 클라이언트 컴포넌트에서 사용할 수 있도록 만들어 줍니다.) 무한 스크롤링을 구현하였습니다.
자세한 설명은 코멘트 달아 두겠습니다 ! 
> Dep 80 fe id cards list

- src/app/id-card/create/page.tsx
- src/components/KeywordInput/KeywordInput.tsx
- src/modules/IdCardCreation/IdCardCreation.type.ts
- src/modules/IdCardCreation/IdCardCreationSteps.tsx
- src/modules/IdCardCreation/Step/BoardingStep.client.tsx
- src/modules/IdCardCreation/Step/CompleteStep.client.tsx
- src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
- src/modules/IdCardCreation/Step/KeywordStep.client.tsx
- src/modules/IdCardCreation/Step/ProfileStep.client.tsx
- 주민증 생성 페이지(`/id-card/create`)를 만듭니다.
- 로딩 페이지가 spec out 되어 삭제합니다.
- 레이아웃 tailwind 추가된 것에 맞게 수정합니다.
- 스타일 수정이 위주여서 테스트 한 번 돌려보시고 넘어가면 될 것 같습니다!
[local](http://localhost:3000/id-card/create)에서 테스트할 수 있습니다.
[Figma](https://www.figma.com/file/TqXqE20VX7V1sw71TYj8qO/DD-_-WIRE-FRAME?type=design&node-id=475-6020&t=to63ZDadqhhJtwo0-4)
> Dep 112 id card creation page

- src/api/domain/idCard.api.ts
- src/app/my-page/edit/page.tsx
- src/app/my-page/page.tsx
- src/mocks/community/community.mockHandler.ts
- src/mocks/handlers.ts
- src/mocks/idCard/idCard.mock.ts
- src/mocks/idCard/idCard.mockHandler.ts
- src/modules/IdCardCreation/Form/IdCardCreationForm.tsx
- src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
- src/modules/IdCardCreation/IdCardCreationSteps.tsx
- src/modules/IdCardCreation/Step/CompleteStep.client.tsx
- src/modules/IdCardCreation/Step/KeywordContentStep.client.tsx
- src/modules/IdCardEditor/IdCardEditorSteps.stories.tsx
- src/types/idCard/request.type.ts
- src/types/idCard/response.type.ts
- id card 생성 post api를 추가합니다.
- poast api에 대한 사용자 id 반환(response)에 따라 동작을 추가합니다.
- mocking 을 추가합니다.
- validation 누락된 부분과 handlesubmit 이 동작하도록 수정합니다.
- api가 전송될 때 버튼이 disable 되도록 만듭니다.
mock handler 처리에 대해서 맞추는 논의가 필요한 것 같습니다. 수요일 회의 때 안건으로 올리겠습니다!
privateApi 가 현재 동작하지 않아 [코드](https://github.com/depromeet/Ding-dong-fe/blob/a1223b4974981670015bac6beb328dcd5e8a02db/src/api/domain/idCard.api.ts#L11)를 publicApi 로 바꾸어야 동작합니다.
[storybook](http://localhost:6006/?path=/story/modules-idcardsteps--default)에서 확인할 수 있습니다.
[Figma](https://www.figma.com/file/TqXqE20VX7V1sw71TYj8qO/DD-_-WIRE-FRAME?type=design&node-id=475-6020&t=to63ZDadqhhJtwo0-4)
[Swagger](http://43.201.214.187/api/swagger-ui/index.html#/%EC%A3%BC%EB%AF%BC%EC%A6%9D/postIdCard)
> Dep 73 idcard create api

- src/api/domain/image.api.ts
- src/components/ProfileImageEdit/ProfileImageEdit.client.tsx
- src/mocks/image/image.mock.ts
- src/mocks/image/image.mockHandler.ts
- src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
- src/modules/IdCardCreation/Step/KeywordContentImage.client.tsx
- src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
- src/types/image/index.ts
- src/types/image/model.type.ts
- src/types/image/request.type.ts
- src/types/image/response.type.ts
- image api 에 사용되는 type을 추가합니다.
- image api를 추가합니다.
- image api를 사용하는 컴포넌트에 추가합니다.
- mocking을 추가합니다.
- publicApi 일 때, local에서 mocking을 추가해 실행할 경우 interceptor 에서 오류가 나는 것 같습니다. storybook에서는 잘 작동합니다.
해당 부분 다음 PR에서 해결하겠습니다. (참고 :  [Salck](https://depromeet13th.slack.com/archives/C052G0MBG3V/p1687079470959039?thread_ts=1687077901.338489&cid=C052G0MBG3V))
privateApi 가 현재 동작하지 않아 [코드](https://github.com/depromeet/Ding-dong-fe/blob/874c45551285a051eccf9b98d438f6ccd8adf8aa/src/api/domain/image.api.ts#L12)를 publicApi 로 바꾸어야 동작합니다.
[storybook](http://localhost:6006/?path=/story/modules-idcardsteps--default)에서 profile image를 변경해 보세요.
[Swagger](http://43.201.214.187/api/swagger-ui/index.html#/%EC%9D%B4%EB%AF%B8%EC%A7%80/uploadImage)
> Dep 116 Add image upload api

- src/components/BottomSheet/BottomSheet.stories.tsx
- src/components/BottomSheet/BottomSheetFooterButton.tsx
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/components/Button/TextButton.stories.tsx
- src/components/Button/TextButton.tsx
- src/components/ConfirmPopup/ConfirmDeleteKeyword/ConfirmDeleteKeyword.client.tsx
- src/components/ConfirmPopup/ConfirmDeleteKeyword/ConfirmDeleteKeyword.stories.tsx
- src/components/ConfirmPopup/ConfirmDeleteKeyword/index.ts
- src/components/ConfirmPopup/ConfirmUnSave/ConfirmUnSave.client.tsx
- src/components/ConfirmPopup/ConfirmUnSave/ConfirmUnSave.stories.tsx
- src/components/ConfirmPopup/ConfirmUnSave/index.ts
- src/components/ConfirmPopup/index.ts
- src/components/ConfirmPopup/useConfirmPopup.ts
- src/components/Popup/Popup.stories.tsx
- src/components/Popup/Popup.tsx
- src/modules/CommunityAdmin/CommunityAdmin.tsx
- src/modules/CommunityAdmin/CommunityAdminEditForm.client.tsx
- src/modules/CommunityProfile/CommunityBgImage.client.tsx
- src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
- src/modules/IdCardCreation/Step/BoardingStep.client.tsx
- src/modules/IdCardCreation/Step/CompleteStep.client.tsx
- src/modules/IdCardEditButton/IdCardEditButton.client.tsx
- src/modules/IdCardEditor/IdCardEditor.tsx
- src/modules/KeywordContentEditCard/KeywordContentEditCard.client.tsx
- src/modules/PlanetEnterButton/PlanetEnterButton.client.tsx
1. 취소 confirm popup 구현
2. 삭제 confirm popup 구현 
3. Button, TextButton (export default -> named export)
키워드 삭제 및 저장하지 않고 페이지를 벗어났을 때 활용할 수 있는 Confirm Popup 컴포넌트를 개발했어요. `주민증 수정`, `키워드 편집 컴포넌트`에 적용했어요.
자세한 동작은 스토리북으로 참고해주세요! 
🚨팝업 및 모달과 관련해서 현재 문제점이 있어요
- 지금은 popup사용하려면 컴포넌트에서 3부분을 건들어야 해요. tsx부분 컴포넌트를 선언하고, 핸들러에 추가하고, usePop으로 열고 닫는 로직을 추가해야해요
```
usePop선언
// 컴포넌트 로직
이벤트 핸들러 선언
// 컴포넌트 로직
jsx에 popup컴포넌트 삽입
```
- add Pop()과 같은 표준화된 로직만 호출하면 jsx부분에 따로 선언할 필요 없이 pop portal에 추가되는 로직을 짜면 어떨까 싶네요
- [Confirm Delete Keyword](https://6478b0e59073c507c3cc3944-dnjvlswsou.chromatic.com/?path=/story/components-confirmdeletekeyword--primary)
- [Confirm Delete Unsave](https://6478b0e59073c507c3cc3944-dnjvlswsou.chromatic.com/?path=/story/components-confirmunsave--primary)
- [주민증 수정에 …
> Dep 119 confirm pop up

- src/modules/CommentList/Comment/Comment.client.tsx
- src/modules/CommentList/CommentCommon/ReplyHideButton.client.tsx
- src/modules/CommentList/CommentCommon/ReplyShowButton.client.tsx
- src/modules/CommentList/CommentCommon/index.ts
답글 보여주기 버튼 기능을 분리했어요. 
-> 답글 숨기기 버튼과 답글 더보기 버튼 
이유: 답글 숨기기버튼은 답글 리스트 맨 하단에 있고, 답글 더보기 버튼은 답글 리스트 맨 상단에 있어서 분리해야해요. 
답글 숨기기하면 알아서 스크롤이 위로 올라와요(의도하지 않았는데 되네요 ㅎㅎ)
[답글 펼치기 스토리](https://6478b0e59073c507c3cc3944-jittrforne.chromatic.com/?path=/story/modules-comment--primary)
댓글 컴포넌트 구조 관련된 내용은 https://github.com/depromeet/Ding-dong-fe/pull/96 를 참고해주세요
> Refactor: 답글 숨기기, 펼치기 버튼 분리

- .storybook/main.ts
- .storybook/preview.tsx
- package.json
- pnpm-lock.yaml
- src/mocks/browser.ts
- src/mocks/handlers.ts
- src/mocks/image/image.mockHandler.ts
- src/mocks/server.ts
- src/modules/IdCardCreation/IdCardCreationSteps.stories.tsx
- storybook에서 privateApi를 사용할 수 있도록 cookie 를 설정합니다.
- preview에 설정된 handler가 overwrite 되지 않도록 key 값을 줍니다. ([Slack](https://depromeet13th.slack.com/archives/C052G0MBG3V/p1687079470959039?thread_ts=1687077901.338489&cid=C052G0MBG3V) 문제 해결)
- cookie 값을 BE에게 받아서 env에 저장합니다. 선 PR 리뷰 먼저 진행 부탁드립니다!
[storybook](http://localhost:6006/?path=/story/modules-idcardsteps--default)에서 public api 사용 시 이미지 변경 및 제출 시 잘 작동하는 것을 확인할 수 있습니다.
[Slack](https://depromeet13th.slack.com/archives/C052G0MBG3V/p1687079470959039?thread_ts=1687077901.338489&cid=C052G0MBG3V)
> Add storybook cookie addon

- src/utils/auth/getUserId.client.ts
- src/utils/auth/getUserId.server.ts
getUserIdClient 관련 빌드 에러를 수정했습니다.
- `Collecting page data ...ReferenceError: document is not defined`에러가 발생하며 빌드가 실패하였고 이를 해결하기 위해 document가 정의되지 않은 경우 처리를 추가했습니다.
- next에서 페이지가 클라이언트에 mount되기 전까지 기다리도록 window !== undefined등의 로직을 많이 사용하는것 같습니다. 
- 서버사이드에서 에러를 던질시 현재 캐치하는 부분이 없어 에러시 -1을 반환하도록 임시로 처리했습니다. 에러를 던질시 빌드에러가 발생합니다.
> feat: getUserIdClient 서버사이드 가드 추가

- src/api/domain/community.api.ts
- src/api/domain/user.api.ts
- src/app/invitation/[code]/page.tsx
- src/components/Template/TemplateButton.tsx
- src/components/Template/TemplateContent.tsx
- src/mocks/user/user.mock.ts
- src/mocks/user/user.mockHandler.ts
- src/types/user/model.type.ts
- src/types/user/request.type.ts
- src/types/user/response.type.ts
- src/utils/auth/getUserId.client.ts
- 초대 코드 검사 및 행성 가입 api를 추가합니다.
- mock을 추가합니다.
- 사용자의 로그인여부를 파악하기 위해 함수를 수정합니다.
- 초대 페이지를 생성합니다.
- 초대 페이지 스타일을 추가합니다.
- 에러 처리는 추후 진행할 예정입니다.
- 비로그인 사용자가 회원가입 후 다시 기존 페이지로 돌아오는 로직은 추후 진행할 예정입니다.
```
pnpm msw // 실행
```
- 비로그인
`/invitation/1`로 들어옴 -> 초대 수락하기 버튼 클릭 -> `/auth/signin`으로 전환
https://github.com/depromeet/Ding-dong-fe/assets/55529617/a9aab33c-dc14-410c-b20c-8c5fb03929ee
- 로그인 + 캐릭터 생성이 되어 있다 가정 ( /auth/signin 에서 로그인 후 실행)
`/invitation/1`로 들어옴 -> 초대 수락하기 버튼 클릭 -> `/planet/id`으로 전환
[초대 flow miro](https://miro.com/app/board/uXjVM7tyQlc=/)
> Dep 167 Add flow of invitation

- src/modules/CommentList/CommentCommon/Content.client.tsx
- src/modules/CommentList/CommentCommon/ReplyShowButton.client.tsx
- 답글이 0개일 때는 답글 펼치기 버튼 안보이게 하기
- 댓글 상세보기가 제대로 동작하지 않은 버그 수정(tw js 변수가 적용되지 않은 문제...)
- 댓글 상세보기 초기 레더링 시 깜빡거리는 불편함 수정 
- useEffect -> useLayoutEffect
- 초기 값 변경
> 답글 없을 때 [답글 보여주기] UI  수정

- src/api/domain/comment.api.ts
- src/modules/CommentList/Comment/Comment.client.tsx
- src/modules/CommentList/CommentCommon/DeleteButton.client.tsx
- src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
- src/utils/commentApi.util.ts
댓글, 대댓글 삭제를 구현했어요.
저번 회의 때 언급했지만, 로직이 좀 복잡해요..
자세한 로직(commentApi.util.ts)보다는 큰 로직위주(comment.api.ts)로 봐주세요!
1. 댓글 삭제
2. 성공시 => X
3. 실패시 => 롤백
----
저번에 댓글 삭제, 대댓글 삭제 컴포넌트를 분리한다고 했는데 코드 중복되는게 있어서, 컴포넌트에 함수를 넘겨주도록 구현해서 코드 중복을 줄였어요. 
`pnpm msw // 실행`
> Dep 176 delete comment

- src/api/config/api.types.ts
- src/api/config/interceptor.ts
- src/mocks/comment/comment.mockHandler.ts
- src/mocks/community/community.mockHandler.ts
- src/mocks/idCard/idCard.mockHandler.ts
- src/mocks/image/image.mockHandler.ts
- src/mocks/mock.util.ts
- src/mocks/notification/notification.mockHandler.ts
- src/mocks/user/user.mockHandler.ts
1. 아래와 같은 서버 기본 타입을 추가했어요. 
```tsx
export type DefaultServerResponseType = {
data: any;
statusCode: number;
success: boolean;
};
```
intercptor의 onResponse에서는 아래와 같이 parsing해요~
논의대로 서버에서 내려주는 statusCode, success를 사용합니당
```tsx
export const onResponse = (response: AxiosResponse) => {
const defaultServerScheme: DefaultServerResponseType = response.data;
const { data, statusCode, success } = defaultServerScheme;
const { headers } = response;
return { ...data, headers, statusCode, success };
};
```
2. mock handler 기본 유틸 response
`src/mocks/mock.util.ts` 에 있습니다
```diff
- return res(ctx.status(200), ctx.json(createCommentCount()));
+ return generateResponse({ statusCode: 200, data: createCommentCount() });
```
> 서버 기본 response 타입 

- src/api/domain/community.api.ts
- src/modules/CommunityAdmin/CommunityAdminEditForm.client.tsx
- src/types/community/response.type.ts
행성 생성/수정 form에 중복 체크 로직을 추가했어요.
서버 응답 형태로 원시값이 넘어오는데, 이경우 onResponse에서 {...data}와 같은 방식으로 전달할 수 없기 때문에 interceptor 응답 형태 #134 가 반영되어야 정상 작동합니다.
> feat: 중복 체크 api 추가

- src/constant/recommendKeyword.ts
- src/modules/IdCardCreation/Step/KeywordStep.client.tsx
- src/modules/IdCardEditor/IdCardEditor.constant.ts
- src/modules/IdCardEditor/Step/EditKeywordStep.client.tsx
주민증 생성 및 주민증 수정에서 사용하는 추천 키워드 constant화
client에서 관리합니당. 선택된 캐릭터마다 다른 추천키워드가 아닌 어떤 유저이든 동일한 추천키워드가 보여지도록 합니다
https://github.com/depromeet/Ding-dong-fe/issues/157
> #157 기본 추천 키워드 관리

- package.json
- pnpm-lock.yaml
- src/modules/Notification/NewNotificationBadge.client.tsx
구독 EventSource에 인증 헤더를 추가했어요.
기본 EventSource는 header를 지원하지 않기 때문에 [폴리필](https://www.npmjs.com/package/event-source-polyfill)을 설치했어요.
> Fix/sse: 구독 인증 추가

- src/app/planet/[communityId]/id-card/create/page.tsx
- src/modules/IdCardCreation/IdCardCreationSteps.tsx
행성만들기 steps에서 communityId추가
- 변경된 폴더 구조에 따라 IdCardCreationSteps의 props로 communityId를 넘겨 받도록 수정했어요
https://github.com/depromeet/Ding-dong-fe/issues/153
> 행성만들기 steps에서 communityId추가

- package.json
- src/api/domain/community.api.ts
- src/app/Provider.tsx
- src/app/invitation/[code]/page.tsx
- src/app/page.tsx
- src/middleware.ts
- src/mocks/community/community.mockHandler.ts
- src/modules/Onboarding/Step/CharacterCompleteStep.client.tsx
- src/utils/auth/getUserId.server.ts
- src/utils/cookie.util.ts
- src/utils/fetch.ts
- src/utils/route/route.ts
- msw가 개발 환경에서만 돌도록 환경변수를 수정합니다.
- "로그인 후 이전 페이지로 돌아가기" 또는 "초대페이지로 들어올 시 해당 초대코드의 행성으로 보내기"를 구현하기 위해 cookie를 사용
- cookie를 다루는 함수 util을 추가합니다.
- 초대 페이지와 onboarding 페이지에 쿠키 및 routing logic을 추가합니다.
- 초대코드가 유효하지 않을 때 에러를 처리합니다.
[Notion](https://www.notion.so/depromeet/834d9f5f03fb4d57885d91d7c3b0f88a)에 테스트 시나리오 적어놓았습니다.
[miro](https://miro.com/app/board/uXjVM7tyQlc=/)
> Fix main flow cookie

- src/app/planet/[communityId]/page.tsx
- src/components/BottomNavigation/BottomNavigation.tsx
- src/hooks/usePlanetNavigate.ts
- src/modules/PlanetSelector/PlanetSelector.client.tsx
여러 이슈가 있는데 요약하면 페이지 전환간 행성 샐랙터 컴포넌트와 동기화가 제대로 안 됨
=> pathname을 활용해서 동기화
#248
> 행성 선택자 및 Bottom sheet 행성 동기화 문제 

- src/modules/CommentList/CommentCommon/UserProfile.client.tsx
- profile image에 `object-cover` css를 추가합니다.
#261
> Add object-cover css on profile user image

- src/api/domain/comment/comment.api.ts
- src/api/domain/comment/comment.helper.ts
- src/mocks/comment/comment.mock.ts
- src/mocks/comment/comment.mockHandler.ts
- src/mocks/user/user.mockHandler.ts
- src/modules/CommentList/Comment/Comment.client.tsx
- src/modules/CommentList/CommentCommon/CommentOptions.client.tsx
- src/modules/CommentList/CommentCommon/ReplyShowButton.client.tsx
- src/modules/CommentList/CommentCommon/index.ts
- src/modules/CommentList/CommentReplyList/CommentReply.client.tsx
- src/modules/CommentList/CommentReplyList/CommentReplyList.client.tsx
- src/types/comment/model.type.ts
- src/types/comment/request.type.ts
- src/types/comment/response.type.ts
1. 댓글 조회와 대댓글 조회 분리
2. 대댓글 작성 낙관적 업데이트 수정
3. 대댓글 제거 낙관적 업데이트 수정
1. 댓글 조회와 대댓글 조회 분리
댓글 스키마에 포함된 대댓글이 별도의 API 요청으로 분리됐어요. 
- 댓글 스키마의 repliesCount가 0 이상일 때만 [답글 더보기] 버튼이 보여져요
- [답글 더보기] 버튼을 눌러서 `src/modules/CommentList/CommentReplyList/CommentReplyList.client.tsx`가 마운트되면 대댓글 요청을 보내요.
2. 대댓글 작성 낙관적 업데이트 수정
요청
- 대댓글을 생성하여 해당 댓글의 대댓글 목록을 업데이트
- 해당 댓글의 대댓글 개수 업데이트
성공
- 대댓글의 id를 실제 서버의 id로 변경
실패
- 이전 대댓글 리스트로 수정
- 이전 댓글의 대댓글 개수로 수정
3. 대댓글 제거 낙관적 업데이트 수정
요청
- 해당 대댓글을 대댓글 목록에서 제거
- 해당 댓글의 대댓글 개수 업데이트
실패
- 이전 대댓글 리스트로 수정
- 이전 댓글의 대댓글 개수로 수정
- [[FE] 작성한 댓글 실시간 업데이트](https://www.notion.so/depromeet/FE-072b3456b9cd41dd834f5c60112eb3e5?pvs=4)
- [[FE] 작성한 댓글 노출](https://www.notion.so/depromeet/FE-0d5d805d89614073a7f7cd29aaac0005?pvs=4)
> 대댓글 API 관련 변경 사항 반영 (대댓글 요청을 댓글 요청과 분리)

- src/modules/IdCard/IdCard.client.tsx
mypage에서 주민증 누르면 주민증 상세보기 되도록 수정하였습니다.
https://www.notion.so/depromeet/FE-585f47056b9246b395b478f7b455d2a4?pvs=4
> Fix: mypage에서 주민증 상세보기 되도록 수정

- .github/workflows/chromatic.yml
- .github/workflows/ci.yml
- pull request가 열릴 때 배포되는 것을 막습니다.
(ec2가 FE, BE 같이 배포할 때 폭파되기 때문에 QA 동안 배포가 많이 일어나는 관계로  CI/CD 조건을 줄이는 것이 목적)
[Slack](https://depromeet13th.slack.com/archives/C0515CGG9H8/p1689000627053719)
> Fix running CI and chromatic only when commits are pushed on main

- src/modules/IdCardEditor/Form/IdCardEditorForm.tsx
- src/modules/IdCardEditor/IdCardEditor.tsx
[모바일 환경] 키워드 입력 부분에서 enter 버튼을 누르면 form이 제출되는 버그 수정
- [ [FE] 주민증 수정 - 키워드 직접 입력 오류](https://www.notion.so/depromeet/FE-59e464fb14cd49a19a052a89a3af1f01?pvs=4)
> refactor: 주민증 수정 form 제출 이벤트 막기

- src/api/domain/idCard.api.ts
- src/modules/IdCardCreation/IdCardCreationSteps.tsx
- 원인 : 하나의 url에서 step으로 관리하고 있었기 때문입니다.
- 해결 : 해당 url로 들어왔을 때, 주민증 생성 여부를 체크하고 완료 step으로 보냅니다.
[Notion](https://www.notion.so/depromeet/FE-b96c0fb92e0847cc81e36279541bd43f)
> Add moving complete step of idcard creation after backward

- src/modules/IdCardCreation/IdCardCreationSteps.tsx
주민증 생성 디폴트 키워드 설정
- 부여 받은 캐릭터별로 선택하지 않아도 자동으로 선택되어있는 디폴트 키워드가 한 개씩 선택
> 주민증 생성 디폴트 키워드

- .vscode/launch.json
- src/components/BottomNavigation/BottomNavigation.tsx
- src/stores/community.store.ts
미들웨어와 쿠키 관련 문제였습니다
관련 이슈 [노션페이지 - middleware, 쿠키](https://www.notion.so/depromeet/middleware-1715e5ba5e4642f285900ed5ccd60ad9?pvs=4)에 정리했어요
요약
- 쿠키가 path에 따라 다르게 지정돼서 middleware에서 설정한 행성 라우팅 로직에서 실행되지 않은 문제였어요 
- bottom nav에서 이동할 때 useCommunityStore에 communityId값을 참고해서 이동하게 수정했어요. 
- 안전하게 하려면 middleware에 "/planet"경로에도 "/"과 같은 로직을 적용해야 해요
https://www.notion.so/depromeet/FE-ad792ee8ec4546ba86bafa9222fbfb64?pvs=4
> 알림 페이지 이동후 다시 홈으로 돌아오면, 원래 있던 행성이 아닌, 행성 목록 중 첫 번째 행성으로 이동합니다

- src/api/config/interceptor.client.ts
- src/api/config/interceptor.server.ts
- src/utils/auth/error.ts
axios interceptor에서 401(인증)에러 일때만 토큰 갱신 로직이 실행되고, 403(인가)에러 일 때는 실행되지 않게 수정했어요
> refactor: 403일 때는 토큰 발급 로직 실행 안되게 수정

- src/components/BottomNavigation/BottomNavigation.tsx
- src/components/BottomSheet/BottomSheet.tsx
- src/components/ToastMessage/ToastMessage.tsx
- src/components/ToastMessage/ToastMessageProvider.tsx
- src/components/TopNavigation/TopNavigationWrapper.tsx
- tailwind.config.js
토스트 알람 최대 길이 수정
- 바텀네비와 탑네비처럼 최대 길이 420px 설정
최대 길이 tailwind 변수 관리 설정
- 420px -> content변수로 설정
- ex. max-w-content
> 토스트 알람 최대 길이 수정 및 최대 길이 tailwind 변수 관리 설정

- src/middleware.ts
- src/modules/PlanetSelector/PlanetSelector.client.tsx
- 딩동 행성의 주민증 생성을 막기 위해 `/planet/1/id-card/create` url로 넘어올 시 ding dong 행성으로 보냅니다.
- 행성 전환 시 `pointer: cursor` 로 스타일을 수정합니다.
> Prevent user creating id card on ding dong planet

- src/app/planet/[communityId]/id-card/[idCardId]/components/Bell/Bell.client.tsx
- src/app/planet/[communityId]/id-card/[idCardId]/components/Bell/Bell.stories.tsx
- src/app/planet/[communityId]/id-card/[idCardId]/components/Bell/Bell.tsx
- src/app/planet/[communityId]/id-card/[idCardId]/components/Bell/Button/BellButton.tsx
- src/app/planet/[communityId]/id-card/[idCardId]/components/Bell/Message/BellMessages.tsx
- src/app/planet/[communityId]/id-card/[idCardId]/components/IdCardDetail/IdCardDetail.tsx
- prop 이름을 변경하고 client prefix를 추가합니다.
- bell message를 누른 후 toast가 나오도록 추가합니다.
- backdrop을 추가합니다.
- 애니메이션을 추가합니다.
`pnpm storybook` + `pnpm msw`로 http://localhost:3000/planet/11/id-card/1 에서 보실 수 있습니다.
[framer motion](https://www.framer.com/motion/)
[Figma](https://www.figma.com/file/h0adZ1H8szR3zpNThEMfm2/DD-_-WIRE-FRAME-(Copy)?type=design&node-id=3268-25220&mode=design&t=Th7sl1TPmkbyplV8-4)
> Add backdrop on bell
